### ISSUE TITLE
_convertAmountDecimalIntegerToHex returning incorrect hex value?

### ISSUE THREAD

**Issue by kilkelly** [marvinroger/nanocurrency-js#15]
When I use `createSendBlock` and provide it with a `balance` in raw the returned hex value seems to be incorrect. 

I provide `2000000000000000000000000` in the `balance` property and the converted value shows `0000000000001A784379D99DB4200000`. The converted value I am expecting is `000000000001A784379D99DB42000000`. You'll see that they look deceptively similar but if you count the number of zeros at the start and end of both figures you will see that the figure has been 'shifted' one place too many.

I guess the bug must be in the `_convertAmountDecimalIntegerToHex` function? Thanks!

**Comment by marvinroger** [comment]
v1.7.3 fixes it.

Thanks a lot! There was a problem in the 128 bits integer handling (an issue with the underlying bignum library, I added a workaround in the C code). Please close once you confirm it works for you!

After that, I think (hope) everything is stable. 😉

**Comment by kilkelly** [comment]
Thanks @marvinroger , that worked perfectly!
