### ISSUE TITLE
work() not working...

### ISSUE THREAD

**Issue by vano21** [marvinroger/nanocurrency-js#19]
I can't get work() to do its thing:

`const pow = nanoCurrency.work(accountHash);`

Outputs:

`nanocurrency.esm.js:6 
    Uncaught (in promise) TypeError: checkHash is not a function
    at Object.work (http://localhost:3000/static/js/bundle.js:25491:182215)`

This is in a react app.

**Comment by marvinroger** [comment]
I did not test the esm bundle, but the cjs and umd ones are working well. Can you provide a full reproduction script (with the imports)?

Also, what’s your module bundler? Webpack?

**Comment by marvinroger** [comment]
And, do you have the problem only with `work` ?

**Comment by vano21** [comment]
These work: generateSeed() and deriveSecretKey()

These do not work (apart from work()): derivePublicKey() and deriveAddress()

they produce a similar error (checkKey is not a function)

Looks like it has something to do with exporting from nano currency.esm.js - the problematic ones seem to be the ones being exported as an alias.

I am using a standard create-react-app generated project.

**Comment by vano21** [comment]
How can I use the cjs/umd ones? I am simply doing:

import * as nanoCurrency from 'nanocurrency';

**Comment by vano21** [comment]
Ok I just did this:

`import * as nanoCurrency from '../node_modules/nanocurrency/dist/nanocurrency.cjs';`

and it all works now.

**Comment by marvinroger** [comment]
There must be a problem in either the Rollup bundling or the Babel transpiling. I implemented a workaround, not exporting aliases but actual wrapper functions. It feels cleaner anyway, so I am comfortable with that.

Can you test with 1.7.4?

**Comment by vano21** [comment]
All ok now!

**Comment by marvinroger** [comment]
Perfect! Thanks. 😉
