### ISSUE TITLE
Provide helpers for converting units

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/nanocurrency-js#22]
The goal of the library is to contain everything needed to deal with the Nano currency. We should add helpers to convert units (Nano, nano, raw, NANO...).

Please vote :+1: if this is important to you.

**Comment by vano21** [comment]
I can't seem to find a helper function for converting amounts to zero-filled hex. I know this is trivial to do, but was thinking since this library is also useful to those who would be making blocks, exporting the helper function _convertAmountDecimalIntegerToHex would probably not be a bad idea?

**Comment by marvinroger** [comment]
Just wondering, what's the point of creating the block yourself when you can use https://github.com/marvinroger/nanocurrency-js/blob/develop/DOCUMENTATION.md#nanocurrencycreateopenblocksecretkey-data--object ?

**Comment by vano21** [comment]
Wasn't aware that the method didn't do PoW. Thanks for letting me know.

**Comment by marvinroger** [comment]
Even if it is kind of optimized with the WebAssembly, it's still very expensive (time-speaking) to compute a PoW, so the library does not compute one when you create a block, you'll have to provide it yourself.

Another reason is that you might already have a PoW precomputed in cache, so you can pass it.

**Comment by marvinroger** [comment]
@kilkelly considering you've :+1: this issue, and you're the author of [nano-prettify](https://github.com/kilkelly/nano-prettify), would you mind if I reuse some of your code? With the proper copyright notice, obviously!

**Comment by kilkelly** [comment]
Sure thing @marvinroger , just include the MIT license and it's cool. Alternatively link it as a package to receive future bug fixes. The choice is completely up to you 💯

**Comment by marvinroger** [comment]
@kilkelly there was some limitation with your code (we can only convert raw to another unit, not the other way around) and the prettify part is out of scope for this library ([Numeral.js](http://numeraljs.com/) does it best), so I ended up coding the convert code myself: https://github.com/marvinroger/nanocurrency-js/blob/a7e66ab50301644fff60444a6dc784f7c5a8bb41/src/conversion.js

Thanks for the permission, though. 😉

**Comment by kilkelly** [comment]
No worries, it was only ever intended to be a raw to unit one-way conversion. Your code looks good, will give it a try soon.

**Comment by marvinroger** [comment]
Released! There's now the [`convert`](https://github.com/marvinroger/nanocurrency-js/blob/master/DOCUMENTATION.md#convert) function. @vano21 it can convert any value from/to hex, as requested.
