### ISSUE TITLE
When .min.js file for browsers?

### ISSUE THREAD

**Issue by bcapinski** [marvinroger/nanocurrency-js#31]
Wizard isn't working right now, and it got me thinking of a specific version for browsers.

**Comment by bcapinski** [comment]
https://cdn.jsdelivr.net/npm/nanocurrency@1.6.1/dist/ does not support universal blocks.

**Comment by marvinroger** [comment]
Well, every version is also available on jsdelivr: https://cdn.jsdelivr.net/npm/nanocurrency@1.10.1/dist/
