### ISSUE TITLE
Unable to create StateOpenBlock

### ISSUE THREAD

**Issue by RyoAkio** [marvinroger/nanocurrency-js#39]
Previous in open state block is empty, but...

nanocurrency-js gives Error: Previous is not valid

**Comment by marvinroger** [comment]
No, take a look: https://github.com/nanocurrency/raiblocks/wiki/Universal-Blocks-Specification

The previous hash must be filled with `0` if it's an "open" block, so just put `0000000000000000000000000000000000000000000000000000000000000000` as `previous`. 😉
