### ISSUE TITLE
Can't create block with balance = "0"

### ISSUE THREAD

**Issue by LilleJohs** [marvinroger/nanocurrency-js#45]
I'm trying to make a send block
`nanocurrency.createBlock(privateKey, {
    balance: "0",
    link: link,
    previous: previous,
    representative: representative,
    work: null
  });`,
but I'm getting a 'Balance is not valid' error. I'm simply trying to send all Nanos away from an account, so balance = "0" should be valid.

**Comment by marvinroger** [comment]
You're right! I'll fix.

**Comment by marvinroger** [comment]
@LilleJohs can you tell me if it's OK for you?
