### ISSUE TITLE
Running nanocurrency.deriveAddress() gives me an error in React Native

### ISSUE THREAD

**Issue by LilleJohs** [marvinroger/nanocurrency-js#49]
I'm trying to run the function `deriveAddress(publicKey)` in React Native, but it throws me an error `TypeError: undefined is not a function (evaluating 'AI(i, null, 5).reverse()')` which originates from `node_modules\nanocurrency\dist\nanocurrency.umd.js:6:36609`.

`nanocurrency.deriveSecretKey(seed, 0);` and `nanocurrency.derivePublicKey(privateKey);` both work fine. So I guess the problem comes from `encodeNanoBase32`?

**Comment by LilleJohs** [comment]
No, I guess this [line](https://github.com/marvinroger/nanocurrency-js/blob/master/src/keys.ts#L109) would be the problem. Still don't see why

**Comment by LilleJohs** [comment]
I'm closing this issues since it seems to be an issue with React Native and not your toolkit. I get the error whenever I'm trying to use .revert() on a Uint8Array

**Comment by LilleJohs** [comment]
I'm closing this issues since it seems to be an issue with React Native and not your toolkit. I get the error whenever I'm trying to use .revert() on a Uint8Array

**Comment by marvinroger** [comment]
@LilleJohs did you open an issue on the React Native repo?

**Comment by LilleJohs** [comment]
No, it's something they are aware of. It seems like TypedArrays are not currently supported by React Native.
