### ISSUE TITLE
Fix checkAddress method!

### ISSUE THREAD

**Issue by vitorcremonez** [marvinroger/nanocurrency-js#50]
The check Address method is broking code when pass address with final "2".
Like: xrb_1hnsabbp31nriywu95mua7pxryj77ucdymzhjoxdireubuztz1jomzr3h6g2

Is expected to return false instead of this -> https://i.imgur.com/Beae8Hj.png

**Comment by marvinroger** [comment]
Indeed! A 0 would fail, too. I’ll fix.
