### ISSUE TITLE
Block work is less than threshold

### ISSUE THREAD

**Issue by bmclain** [marvinroger/nanocurrency-js#54]
I'm trying to generate blocks using an external signing service but I'm running into an issue when I attempt to run the `process` rpc command on the payload that I craft. Here's a general outline of the code:

```const nano = require('nanocurrency');
const accountInfo = await rpc.request('account_info', {
    representative: true,
    account,
});
const accountBalance = new BigNumber(accountInfo.balance);
const balance = new BigNumber(accountInfo.balance).minus(amount);
const params = {
    type: 'state',
    previous: accountInfo.frontier,
    account: account,
    representative: accountInfo.representative,
    balance: balance.toString(10),
    link: withdrawToAddress,
};
const blockHash = await nano.hashBlock(params);
params.signature = nano.signBlock({ hash: blockHash, secretKey });
const workResult = await rpc.request('work_generate', { hash: blockHash });
params.work = workResult.work;
const res = await rpc.request('process', { block: JSON.stringify(params) });
```

When I attempt to run `process` it gives me an error back saying `Block work is less than threshold`.

Some folks on the nano discord suggested that I instead input the previous blocks hash (i.e. accountInfo.frontier) into the `work_generate` RPC call, but then I get the error `Bad signature`. Any ideas where I'm going wrong? If I run `create_block` via RPC with these same values (type, previous, account, representative, balance, link, key == secretKey) it generates a valid block that can be sent, but my way using nanocurrency doesn't seem to work.

Any help or ideas you may have would be exceptionally helpful! I wouldn't mind writing a few examples for this project if you'd like to have some?

**Comment by bmclain** [comment]
I included the signing code for clarity but it's actually an external function that is called out to. The main code doesn't have access to the secret keys, otherwise I'd use createBlock.

**Comment by marvinroger** [comment]
Just duplicate the `createBlock()` function, and get the `const publicKey` and `const signature` from your external signing service. Use a `work` value for the previous block on the chain, and it'll work.

**Comment by bmclain** [comment]
I found the problem. I wasn't converting the link, and as we both noted above I wasn't using the frontier for calculating work. It also didn't help that the docker volume of the signatory server had cached an old seed ;)

Thanks for your help, this is a great library!

**Comment by bmclain** [comment]
@marvinroger this is working for send block (I duplicated your `createBlock` code to put the signing code in there) but for receive blocks it's giving me the same error "Block work is less than threshold". I'm using 64 0's for the `previous` field, and am calculating the POW on those 64 zero's. `link` is the sending blocks hash and `link_as_account` is including in my `process` rpc call. I've also confirmed in my signing code that I'm deriving the correct private key for the address by ensuring the private key used for signing derives to the address in the `account` field of the receive block.

Here is an example (with some values modified) of what is being sent to `process`:

```
{ 
     type: 'state',
     account: 'xrb_1a8azyhsc8ptzhytboc7nstgzseusenhrqzahhed8ynt8opi5gqs4hmobrmt',
     previous: '0000000000000000000000000000000000000000000000000000000000000000',
     representative: 'xrb_1awsn43we17c1oshdru4azeqjz9wii41dy8npubm4rg11so7dx3jtqgoeahy',
     balance: '10000000000000000000000000',
     link: '0723F49E8D33FC931812A8CBBEE25C0612EECEDB0EEF70D4E93073629C4CB94D',
     link_as_account: 'xrb_13s5ykaatezwkge37c8dquj7r3ikxu9fp5qhg5cgke5mecg6sgcfic7d4o76',
     work: 'c9f21169177a9a56',
     signature: '5675AB74056EC5C03CA06DDEB1918E4BF8B19E2E5F61A03F38AF700501470F6146D1B29F882EDD4D9D96267BFCB6BA1D2AD8E8F59F2C82630094776D8C3E1402' 
}
```

As I said, I'm using a copy pasted version of your createBlock code and am not totally sure where the issue lay. Any ideas you might have would be extremely welcome!

**Comment by marvinroger** [comment]
@bmclain if this is the first block (legacy *open* block), you don't generate a PoW against `0...0`, but against the account's public key. And, for all subsequent blocks, against the previous block hash.

**Comment by bmclain** [comment]
@marvinroger thank you as always!
