### ISSUE TITLE
Add new feature to help check if a indexAccount is valid

### ISSUE THREAD

**Issue by vitorcremonez** [marvinroger/nanocurrency-js#56]
Would be nice if include to this project a **checkIndex(input)** method to validate if input is a valid account index!

**Comment by vitorcremonez** [comment]
It is something simple, just like that:

```
checkIndex = (input) => {
        return (input >= 0 && input < Math.pow(2,32));
};
```

**Comment by marvinroger** [comment]
My bad, indeed, the max seems to be `Math.pow(2, 32) - 1`. I don't know why nanode (the above link) says otherwise.

Anyway, added in `nanocurrency@2.2.0`.
