### ISSUE TITLE
Feature request add schnorr MuSig N of N

### ISSUE THREAD

**Issue by Onefox** [marvinroger/nanocurrency-js#58]
It would be really nice if this lib could support the schnorr MuSig implementation and enable a user friendly api to create and spend from multisigs.

There is a Rust implementation on the nano github [here](https://github.com/nanocurrency/musig-nano).

There is also the paper and documentation on the blockstream blog [here](https://blockstream.com/2018/01/23/musig-key-aggregation-schnorr-signatures.html).

**Comment by marvinroger** [comment]
I don't want to support something that's not standard (or not universally accepted). Moreover, I'd like the library to stay as unbloated as possible.

If MuSig gains traction, I'd probably reconsider.
