### ISSUE TITLE
Split module to have a separate module for the CLI

### ISSUE THREAD

**Issue by roccomuso** [marvinroger/nanocurrency-js#60]
Wouldn't be better to split and have a separate module for the CLI, like `nanocurrency-cli`?
So that programmatic usage won't bring in `yargs` dependencies tree.

**Comment by marvinroger** [comment]
You are right! Will do when I'll find the time to.

**Comment by roccomuso** [comment]
Feel free to create repo and add me as contributor and I'll help you

**Comment by marvinroger** [comment]
I'd better go with a monorepo approach, with Yarn workspaces and Lerna. What do you think?

**Comment by roccomuso** [comment]
It's fine to use lerna

**Comment by marvinroger** [comment]
@roccomuso done and released on npm. 😉
