### ISSUE TITLE
checkString in convert is useles

### ISSUE THREAD

**Issue by Sekhmet** [marvinroger/nanocurrency-js#70]
https://github.com/marvinroger/nanocurrency-js/blob/69d1d47f3f3137945c3a22e5e7860881be904682/packages/nanocurrency/src/conversion.ts#L70

`checkString` is not invoked so this error will never be thrown.
I'm not sure if this conditional is necessary. `RegExp.test` will return `false` on non-string values and `checkNumber` already checks if `value` is a string.

**Comment by marvinroger** [comment]
@Sekhmet you're right, that's a typo. It's not used today, so we can remove it anyway.

Can you open a PR?

**Comment by marvinroger** [comment]
Fixed in 2.4.0, thanks for the report!
