### ISSUE TITLE
Validate work invalid for new PoW threshold introduced in v21

### ISSUE THREAD

**Issue by Joohansson** [marvinroger/nanocurrency-js#78]
Referring to this: https://github.com/marvinroger/nanocurrency-js/blob/master/packages/nanocurrency/src/work.ts

WORK_THRESHOLD of 0xffffffc000000000 is the default threshold but v21 is introducing a reduced threshold for receive blocks that is 1/8x the default one, that is 0xfffffe0000000000. Validate work will thus be invalid for those blocks. I'm not sure what the best approach is. Lower the threshold or add another parameter to pass in a custom threshold. For the latter, you can then verify against any threshold you want.

**Comment by marvinroger** [comment]
Released in 2.4.0, with a `threshold` parameter. Thanks!
