### ISSUE TITLE
computeWork Minimum Threshold parameter

### ISSUE THREAD

**Issue by thelamer** [marvinroger/nanocurrency-js#85]
Is it possible to pass a minimum Threshold for work? 
I see check got it patched in not sure how to achieve the same thing with compute.

**Comment by marvinroger** [comment]
The #73 PR is a Rust rewrite of the WASM component, and it [supports specifying a min threshold](https://github.com/marvinroger/nanocurrency-js/pull/73/files#diff-088a040b61cfa06179fbdc3f2d255d7a). I'd say the rewrite is almost done, but I don't have enough time currently to release the new package. Currently, unfortunately, there's no way to do that. 😕

**Comment by thelamer** [comment]
Understood and thanks for the info, do you have any bullet points on what is left to do or test ?

**Comment by thelamer** [comment]
Just a heads up V21 just dropped, according to the team they are 6-8 weeks out from dropping the epoch blocks with new work requirements. 
Just logging the info I got in discord to this issue.

**Comment by Joohansson** [comment]
Worst case if the v21 change is done before the WASM can be updated, I would say at least change the default value of 0xffffffc000000000 to fffffff800000000. That corresponds to 8x in difficulty. Seen it hardcoded in at least two places.

**Comment by marvinroger** [comment]
Fixed in `2.5.0`, there's a new `workThreshold` parameter in `computeWork()`.
The Rust rewrite is not ready yet, so I added the feature to the existing Emscripten code. 
Thanks for the heads up! 😉

**Comment by Joohansson** [comment]
Tested and works fine, thank you!
